// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.CityDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CityIntegrationTest: @Transactional;
    
    @Autowired
    private CityDataOnDemand CityIntegrationTest.dod;
    
    @Test
    public void CityIntegrationTest.testCountCitys() {
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", dod.getRandomCity());
        long count = com.gbd.union.domain.City.countCitys();
        org.junit.Assert.assertTrue("Counter for 'City' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CityIntegrationTest.testFindCity() {
        com.gbd.union.domain.City obj = dod.getRandomCity();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to provide an identifier", id);
        obj = com.gbd.union.domain.City.findCity(id);
        org.junit.Assert.assertNotNull("Find method for 'City' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'City' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CityIntegrationTest.testFindAllCitys() {
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", dod.getRandomCity());
        long count = com.gbd.union.domain.City.countCitys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'City', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.City> result = com.gbd.union.domain.City.findAllCitys();
        org.junit.Assert.assertNotNull("Find all method for 'City' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'City' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CityIntegrationTest.testFindCityEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", dod.getRandomCity());
        long count = com.gbd.union.domain.City.countCitys();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.City> result = com.gbd.union.domain.City.findCityEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'City' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'City' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CityIntegrationTest.testFlush() {
        com.gbd.union.domain.City obj = dod.getRandomCity();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to provide an identifier", id);
        obj = com.gbd.union.domain.City.findCity(id);
        org.junit.Assert.assertNotNull("Find method for 'City' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCity(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'City' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CityIntegrationTest.testMerge() {
        com.gbd.union.domain.City obj = dod.getRandomCity();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to provide an identifier", id);
        obj = com.gbd.union.domain.City.findCity(id);
        boolean modified =  dod.modifyCity(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.City merged = (com.gbd.union.domain.City) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'City' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CityIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", dod.getRandomCity());
        com.gbd.union.domain.City obj = dod.getNewTransientCity(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'City' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'City' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CityIntegrationTest.testRemove() {
        com.gbd.union.domain.City obj = dod.getRandomCity();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'City' failed to provide an identifier", id);
        obj = com.gbd.union.domain.City.findCity(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'City' with identifier '" + id + "'", com.gbd.union.domain.City.findCity(id));
    }
    
}
