// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.ContactType;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect ContactTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContactTypeDataOnDemand: @Component;
    
    private Random ContactTypeDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ContactType> ContactTypeDataOnDemand.data;
    
    public ContactType ContactTypeDataOnDemand.getNewTransientContactType(int index) {
        com.gbd.union.domain.ContactType obj = new com.gbd.union.domain.ContactType();
        java.lang.String name = "name_" + index;
        if (name.length() > 20) {
            name  = name.substring(0, 20);
        }
        obj.setName(name);
        return obj;
    }
    
    public ContactType ContactTypeDataOnDemand.getSpecificContactType(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ContactType obj = data.get(index);
        return ContactType.findContactType(obj.getId());
    }
    
    public ContactType ContactTypeDataOnDemand.getRandomContactType() {
        init();
        ContactType obj = data.get(rnd.nextInt(data.size()));
        return ContactType.findContactType(obj.getId());
    }
    
    public boolean ContactTypeDataOnDemand.modifyContactType(ContactType obj) {
        return false;
    }
    
    public void ContactTypeDataOnDemand.init() {
        data = com.gbd.union.domain.ContactType.findContactTypeEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ContactType' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.gbd.union.domain.ContactType>();
        for (int i = 0; i < 10; i++) {
            com.gbd.union.domain.ContactType obj = getNewTransientContactType(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
