// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.ProvinceDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProvinceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProvinceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProvinceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProvinceIntegrationTest: @Transactional;
    
    @Autowired
    private ProvinceDataOnDemand ProvinceIntegrationTest.dod;
    
    @Test
    public void ProvinceIntegrationTest.testCountProvinces() {
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", dod.getRandomProvince());
        long count = com.gbd.union.domain.Province.countProvinces();
        org.junit.Assert.assertTrue("Counter for 'Province' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProvinceIntegrationTest.testFindProvince() {
        com.gbd.union.domain.Province obj = dod.getRandomProvince();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Province.findProvince(id);
        org.junit.Assert.assertNotNull("Find method for 'Province' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Province' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProvinceIntegrationTest.testFindAllProvinces() {
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", dod.getRandomProvince());
        long count = com.gbd.union.domain.Province.countProvinces();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Province', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.Province> result = com.gbd.union.domain.Province.findAllProvinces();
        org.junit.Assert.assertNotNull("Find all method for 'Province' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Province' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProvinceIntegrationTest.testFindProvinceEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", dod.getRandomProvince());
        long count = com.gbd.union.domain.Province.countProvinces();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.Province> result = com.gbd.union.domain.Province.findProvinceEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Province' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Province' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProvinceIntegrationTest.testFlush() {
        com.gbd.union.domain.Province obj = dod.getRandomProvince();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Province.findProvince(id);
        org.junit.Assert.assertNotNull("Find method for 'Province' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProvince(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Province' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProvinceIntegrationTest.testMerge() {
        com.gbd.union.domain.Province obj = dod.getRandomProvince();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Province.findProvince(id);
        boolean modified =  dod.modifyProvince(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.Province merged = (com.gbd.union.domain.Province) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Province' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProvinceIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", dod.getRandomProvince());
        com.gbd.union.domain.Province obj = dod.getNewTransientProvince(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Province' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Province' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProvinceIntegrationTest.testRemove() {
        com.gbd.union.domain.Province obj = dod.getRandomProvince();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Province' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Province.findProvince(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Province' with identifier '" + id + "'", com.gbd.union.domain.Province.findProvince(id));
    }
    
}
