// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.RuleDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RuleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RuleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RuleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RuleIntegrationTest: @Transactional;
    
    @Autowired
    private RuleDataOnDemand RuleIntegrationTest.dod;
    
    @Test
    public void RuleIntegrationTest.testCountRules() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", dod.getRandomRule());
        long count = com.gbd.union.domain.Rule.countRules();
        org.junit.Assert.assertTrue("Counter for 'Rule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RuleIntegrationTest.testFindRule() {
        com.gbd.union.domain.Rule obj = dod.getRandomRule();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Rule.findRule(id);
        org.junit.Assert.assertNotNull("Find method for 'Rule' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Rule' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RuleIntegrationTest.testFindAllRules() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", dod.getRandomRule());
        long count = com.gbd.union.domain.Rule.countRules();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Rule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.Rule> result = com.gbd.union.domain.Rule.findAllRules();
        org.junit.Assert.assertNotNull("Find all method for 'Rule' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Rule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RuleIntegrationTest.testFindRuleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", dod.getRandomRule());
        long count = com.gbd.union.domain.Rule.countRules();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.Rule> result = com.gbd.union.domain.Rule.findRuleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Rule' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Rule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RuleIntegrationTest.testFlush() {
        com.gbd.union.domain.Rule obj = dod.getRandomRule();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Rule.findRule(id);
        org.junit.Assert.assertNotNull("Find method for 'Rule' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Rule' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RuleIntegrationTest.testMerge() {
        com.gbd.union.domain.Rule obj = dod.getRandomRule();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Rule.findRule(id);
        boolean modified =  dod.modifyRule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.Rule merged = (com.gbd.union.domain.Rule) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Rule' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RuleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", dod.getRandomRule());
        com.gbd.union.domain.Rule obj = dod.getNewTransientRule(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Rule' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Rule' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RuleIntegrationTest.testRemove() {
        com.gbd.union.domain.Rule obj = dod.getRandomRule();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rule' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Rule.findRule(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Rule' with identifier '" + id + "'", com.gbd.union.domain.Rule.findRule(id));
    }
    
}
