// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.StatusTypeDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StatusTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StatusTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StatusTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: StatusTypeIntegrationTest: @Transactional;
    
    @Autowired
    private StatusTypeDataOnDemand StatusTypeIntegrationTest.dod;
    
    @Test
    public void StatusTypeIntegrationTest.testCountStatusTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", dod.getRandomStatusType());
        long count = com.gbd.union.domain.StatusType.countStatusTypes();
        org.junit.Assert.assertTrue("Counter for 'StatusType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StatusTypeIntegrationTest.testFindStatusType() {
        com.gbd.union.domain.StatusType obj = dod.getRandomStatusType();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.StatusType.findStatusType(id);
        org.junit.Assert.assertNotNull("Find method for 'StatusType' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'StatusType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StatusTypeIntegrationTest.testFindAllStatusTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", dod.getRandomStatusType());
        long count = com.gbd.union.domain.StatusType.countStatusTypes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'StatusType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.StatusType> result = com.gbd.union.domain.StatusType.findAllStatusTypes();
        org.junit.Assert.assertNotNull("Find all method for 'StatusType' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'StatusType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StatusTypeIntegrationTest.testFindStatusTypeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", dod.getRandomStatusType());
        long count = com.gbd.union.domain.StatusType.countStatusTypes();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.StatusType> result = com.gbd.union.domain.StatusType.findStatusTypeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'StatusType' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'StatusType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StatusTypeIntegrationTest.testFlush() {
        com.gbd.union.domain.StatusType obj = dod.getRandomStatusType();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.StatusType.findStatusType(id);
        org.junit.Assert.assertNotNull("Find method for 'StatusType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStatusType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'StatusType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatusTypeIntegrationTest.testMerge() {
        com.gbd.union.domain.StatusType obj = dod.getRandomStatusType();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.StatusType.findStatusType(id);
        boolean modified =  dod.modifyStatusType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.StatusType merged = (com.gbd.union.domain.StatusType) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'StatusType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatusTypeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", dod.getRandomStatusType());
        com.gbd.union.domain.StatusType obj = dod.getNewTransientStatusType(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'StatusType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'StatusType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StatusTypeIntegrationTest.testRemove() {
        com.gbd.union.domain.StatusType obj = dod.getRandomStatusType();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StatusType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.StatusType.findStatusType(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'StatusType' with identifier '" + id + "'", com.gbd.union.domain.StatusType.findStatusType(id));
    }
    
}
