// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Company;
import com.gbd.union.reference.ChannelType;
import com.gbd.union.reference.CommandType;
import com.gbd.union.reference.ServiceProvider;
import java.lang.Integer;
import java.lang.String;

privileged aspect Channel_Roo_JavaBean {
    
    public String Channel.getSpcode() {
        return this.spcode;
    }
    
    public void Channel.setSpcode(String spcode) {
        this.spcode = spcode;
    }
    
    public String Channel.getServiceId() {
        return this.serviceId;
    }
    
    public void Channel.setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    
    public String Channel.getCommand() {
        return this.command;
    }
    
    public void Channel.setCommand(String command) {
        this.command = command;
    }
    
    public CommandType Channel.getCommandType() {
        return this.commandType;
    }
    
    public void Channel.setCommandType(CommandType commandType) {
        this.commandType = commandType;
    }
    
    public Integer Channel.getFee() {
        return this.fee;
    }
    
    public void Channel.setFee(Integer fee) {
        this.fee = fee;
    }
    
    public String Channel.getServiceProvince() {
        return this.serviceProvince;
    }
    
    public void Channel.setServiceProvince(String serviceProvince) {
        this.serviceProvince = serviceProvince;
    }
    
    public String Channel.getConfirmProvince() {
        return this.confirmProvince;
    }
    
    public void Channel.setConfirmProvince(String confirmProvince) {
        this.confirmProvince = confirmProvince;
    }
    
    public ChannelType Channel.getChannelType() {
        return this.channelType;
    }
    
    public void Channel.setChannelType(ChannelType channelType) {
        this.channelType = channelType;
    }
    
    public ServiceProvider Channel.getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void Channel.setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }
    
    public Company Channel.getCompany() {
        return this.company;
    }
    
    public void Channel.setCompany(Company company) {
        this.company = company;
    }
    
}
