// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Channel;
import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect Channel_Roo_Finder {
    
    public static TypedQuery<Channel> Channel.findChannelsByCommand(String command) {
        if (command == null || command.length() == 0) throw new IllegalArgumentException("The command argument is required");
        EntityManager em = Channel.entityManager();
        TypedQuery<Channel> q = em.createQuery("SELECT Channel FROM Channel AS channel WHERE channel.command = :command", Channel.class);
        q.setParameter("command", command);
        return q;
    }
    
    public static TypedQuery<Channel> Channel.findChannelsBySpcode(String spcode) {
        if (spcode == null || spcode.length() == 0) throw new IllegalArgumentException("The spcode argument is required");
        EntityManager em = Channel.entityManager();
        TypedQuery<Channel> q = em.createQuery("SELECT Channel FROM Channel AS channel WHERE channel.spcode = :spcode", Channel.class);
        q.setParameter("spcode", spcode);
        return q;
    }
    
}
