// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Province;
import java.lang.String;

privileged aspect City_Roo_JavaBean {
    
    public String City.getName() {
        return this.name;
    }
    
    public void City.setName(String name) {
        this.name = name;
    }
    
    public String City.getZIP() {
        return this.ZIP;
    }
    
    public void City.setZIP(String ZIP) {
        this.ZIP = ZIP;
    }
    
    public Province City.getProvince() {
        return this.province;
    }
    
    public void City.setProvince(Province province) {
        this.province = province;
    }
    
}
