// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import java.lang.String;

privileged aspect City_Roo_ToString {
    
    public String City.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Version: ").append(getVersion()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("ZIP: ").append(getZIP()).append(", ");
        sb.append("Province: ").append(getProvince());
        return sb.toString();
    }
    
}
