// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Person;
import com.gbd.union.reference.CompanyType;
import java.lang.String;

privileged aspect Company_Roo_JavaBean {
    
    public String Company.getName() {
        return this.name;
    }
    
    public void Company.setName(String name) {
        this.name = name;
    }
    
    public String Company.getAddress() {
        return this.address;
    }
    
    public void Company.setAddress(String address) {
        this.address = address;
    }
    
    public CompanyType Company.getCompanyType() {
        return this.companyType;
    }
    
    public void Company.setCompanyType(CompanyType companyType) {
        this.companyType = companyType;
    }
    
    public String Company.getBankUserName() {
        return this.bankUserName;
    }
    
    public void Company.setBankUserName(String bankUserName) {
        this.bankUserName = bankUserName;
    }
    
    public String Company.getBankName() {
        return this.bankName;
    }
    
    public void Company.setBankName(String bankName) {
        this.bankName = bankName;
    }
    
    public String Company.getBankAddress() {
        return this.bankAddress;
    }
    
    public void Company.setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }
    
    public String Company.getBankNumber() {
        return this.bankNumber;
    }
    
    public void Company.setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber;
    }
    
    public Person Company.getPerson() {
        return this.person;
    }
    
    public void Company.setPerson(Person person) {
        this.person = person;
    }
    
}
