// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import java.lang.String;

privileged aspect Company_Roo_ToString {
    
    public String Company.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Version: ").append(getVersion()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Address: ").append(getAddress()).append(", ");
        sb.append("CompanyType: ").append(getCompanyType()).append(", ");
        sb.append("BankUserName: ").append(getBankUserName()).append(", ");
        sb.append("BankName: ").append(getBankName()).append(", ");
        sb.append("BankAddress: ").append(getBankAddress()).append(", ");
        sb.append("BankNumber: ").append(getBankNumber()).append(", ");
        sb.append("Person: ").append(getPerson());
        return sb.toString();
    }
    
}
