// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Company;
import com.gbd.union.domain.ContactType;
import java.lang.String;

privileged aspect Contact_Roo_JavaBean {
    
    public String Contact.getName() {
        return this.name;
    }
    
    public void Contact.setName(String name) {
        this.name = name;
    }
    
    public String Contact.getMobile() {
        return this.mobile;
    }
    
    public void Contact.setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    public String Contact.getQq() {
        return this.qq;
    }
    
    public void Contact.setQq(String qq) {
        this.qq = qq;
    }
    
    public String Contact.getEmail() {
        return this.email;
    }
    
    public void Contact.setEmail(String email) {
        this.email = email;
    }
    
    public ContactType Contact.getContactType() {
        return this.contactType;
    }
    
    public void Contact.setContactType(ContactType contactType) {
        this.contactType = contactType;
    }
    
    public Company Contact.getCompany() {
        return this.company;
    }
    
    public void Contact.setCompany(Company company) {
        this.company = company;
    }
    
}
