// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import java.lang.String;

privileged aspect ContactType_Roo_JavaBean {
    
    public String ContactType.getName() {
        return this.name;
    }
    
    public void ContactType.setName(String name) {
        this.name = name;
    }
    
}
