// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.City;
import java.lang.Integer;

privileged aspect MobileCity_Roo_JavaBean {
    
    public Integer MobileCity.getMobilePrefix() {
        return this.mobilePrefix;
    }
    
    public void MobileCity.setMobilePrefix(Integer mobilePrefix) {
        this.mobilePrefix = mobilePrefix;
    }
    
    public City MobileCity.getCity() {
        return this.city;
    }
    
    public void MobileCity.setCity(City city) {
        this.city = city;
    }
    
}
