// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Province;
import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect Province_Roo_Finder {
    
    public static TypedQuery<Province> Province.findProvincesByNameLike(String name) {
        if (name == null || name.length() == 0) throw new IllegalArgumentException("The name argument is required");
        name = name.replace('*', '%');
        if (name.charAt(0) != '%') {
            name = "%" + name;
        }
        if (name.charAt(name.length() -1) != '%') {
            name = name + "%";
        }
        EntityManager em = Province.entityManager();
        TypedQuery<Province> q = em.createQuery("SELECT Province FROM Province AS province WHERE LOWER(province.name) LIKE LOWER(:name)", Province.class);
        q.setParameter("name", name);
        return q;
    }
    
}
