// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import java.lang.String;

privileged aspect Res_Roo_ToString {
    
    public String Res.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Version: ").append(getVersion()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Res_type: ").append(getRes_type()).append(", ");
        sb.append("Res_string: ").append(getRes_string()).append(", ");
        sb.append("Priority: ").append(getPriority()).append(", ");
        sb.append("Descn: ").append(getDescn());
        return sb.toString();
    }
    
}
