// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Person;
import com.gbd.union.domain.Res;
import java.lang.String;
import java.util.Set;

privileged aspect Rule_Roo_JavaBean {
    
    public String Rule.getName() {
        return this.name;
    }
    
    public void Rule.setName(String name) {
        this.name = name;
    }
    
    public String Rule.getDescn() {
        return this.descn;
    }
    
    public void Rule.setDescn(String descn) {
        this.descn = descn;
    }
    
    public Set<Res> Rule.getRes() {
        return this.res;
    }
    
    public void Rule.setRes(Set<Res> res) {
        this.res = res;
    }
    
    public Set<Person> Rule.getPerson() {
        return this.person;
    }
    
    public void Rule.setPerson(Set<Person> person) {
        this.person = person;
    }
    
}
