// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Rule;
import java.lang.Integer;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Rule_Roo_Entity {
    
    @PersistenceContext
    transient EntityManager Rule.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer Rule.id;
    
    @Version
    @Column(name = "version")
    private Integer Rule.version;
    
    public Integer Rule.getId() {
        return this.id;
    }
    
    public void Rule.setId(Integer id) {
        this.id = id;
    }
    
    public Integer Rule.getVersion() {
        return this.version;
    }
    
    public void Rule.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void Rule.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Rule.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Rule attached = this.entityManager.find(this.getClass(), this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Rule.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public Rule Rule.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Rule merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Rule.entityManager() {
        EntityManager em = new Rule().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Rule.countRules() {
        return entityManager().createQuery("select count(o) from Rule o", Long.class).getSingleResult();
    }
    
    public static List<Rule> Rule.findAllRules() {
        return entityManager().createQuery("select o from Rule o", Rule.class).getResultList();
    }
    
    public static Rule Rule.findRule(Integer id) {
        if (id == null) return null;
        return entityManager().find(Rule.class, id);
    }
    
    public static List<Rule> Rule.findRuleEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("select o from Rule o", Rule.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
