// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.ContactTypeDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContactTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContactTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContactTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ContactTypeIntegrationTest: @Transactional;
    
    @Autowired
    private ContactTypeDataOnDemand ContactTypeIntegrationTest.dod;
    
    @Test
    public void ContactTypeIntegrationTest.testCountContactTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", dod.getRandomContactType());
        long count = com.gbd.union.domain.ContactType.countContactTypes();
        org.junit.Assert.assertTrue("Counter for 'ContactType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContactTypeIntegrationTest.testFindContactType() {
        com.gbd.union.domain.ContactType obj = dod.getRandomContactType();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.ContactType.findContactType(id);
        org.junit.Assert.assertNotNull("Find method for 'ContactType' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ContactType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContactTypeIntegrationTest.testFindAllContactTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", dod.getRandomContactType());
        long count = com.gbd.union.domain.ContactType.countContactTypes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ContactType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.ContactType> result = com.gbd.union.domain.ContactType.findAllContactTypes();
        org.junit.Assert.assertNotNull("Find all method for 'ContactType' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ContactType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContactTypeIntegrationTest.testFindContactTypeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", dod.getRandomContactType());
        long count = com.gbd.union.domain.ContactType.countContactTypes();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.ContactType> result = com.gbd.union.domain.ContactType.findContactTypeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ContactType' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ContactType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContactTypeIntegrationTest.testFlush() {
        com.gbd.union.domain.ContactType obj = dod.getRandomContactType();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.ContactType.findContactType(id);
        org.junit.Assert.assertNotNull("Find method for 'ContactType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContactType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ContactType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactTypeIntegrationTest.testMerge() {
        com.gbd.union.domain.ContactType obj = dod.getRandomContactType();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.ContactType.findContactType(id);
        boolean modified =  dod.modifyContactType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.ContactType merged = (com.gbd.union.domain.ContactType) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ContactType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactTypeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", dod.getRandomContactType());
        com.gbd.union.domain.ContactType obj = dod.getNewTransientContactType(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ContactType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ContactType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContactTypeIntegrationTest.testRemove() {
        com.gbd.union.domain.ContactType obj = dod.getRandomContactType();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ContactType' failed to provide an identifier", id);
        obj = com.gbd.union.domain.ContactType.findContactType(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ContactType' with identifier '" + id + "'", com.gbd.union.domain.ContactType.findContactType(id));
    }
    
}
