// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.CPRoleDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CPRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CPRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CPRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CPRoleIntegrationTest: @Transactional;
    
    @Autowired
    private CPRoleDataOnDemand CPRoleIntegrationTest.dod;
    
    @Test
    public void CPRoleIntegrationTest.testCountCPRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", dod.getRandomCPRole());
        long count = com.gbd.union.domain.CPRole.countCPRoles();
        org.junit.Assert.assertTrue("Counter for 'CPRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CPRoleIntegrationTest.testFindCPRole() {
        com.gbd.union.domain.CPRole obj = dod.getRandomCPRole();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to provide an identifier", id);
        obj = com.gbd.union.domain.CPRole.findCPRole(id);
        org.junit.Assert.assertNotNull("Find method for 'CPRole' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CPRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CPRoleIntegrationTest.testFindAllCPRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", dod.getRandomCPRole());
        long count = com.gbd.union.domain.CPRole.countCPRoles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CPRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.CPRole> result = com.gbd.union.domain.CPRole.findAllCPRoles();
        org.junit.Assert.assertNotNull("Find all method for 'CPRole' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CPRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CPRoleIntegrationTest.testFindCPRoleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", dod.getRandomCPRole());
        long count = com.gbd.union.domain.CPRole.countCPRoles();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.CPRole> result = com.gbd.union.domain.CPRole.findCPRoleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CPRole' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CPRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CPRoleIntegrationTest.testFlush() {
        com.gbd.union.domain.CPRole obj = dod.getRandomCPRole();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to provide an identifier", id);
        obj = com.gbd.union.domain.CPRole.findCPRole(id);
        org.junit.Assert.assertNotNull("Find method for 'CPRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCPRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CPRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CPRoleIntegrationTest.testMerge() {
        com.gbd.union.domain.CPRole obj = dod.getRandomCPRole();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to provide an identifier", id);
        obj = com.gbd.union.domain.CPRole.findCPRole(id);
        boolean modified =  dod.modifyCPRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.CPRole merged = (com.gbd.union.domain.CPRole) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'CPRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CPRoleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", dod.getRandomCPRole());
        com.gbd.union.domain.CPRole obj = dod.getNewTransientCPRole(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CPRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CPRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CPRoleIntegrationTest.testRemove() {
        com.gbd.union.domain.CPRole obj = dod.getRandomCPRole();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CPRole' failed to provide an identifier", id);
        obj = com.gbd.union.domain.CPRole.findCPRole(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CPRole' with identifier '" + id + "'", com.gbd.union.domain.CPRole.findCPRole(id));
    }
    
}
