// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.ParamDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParamIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParamIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParamIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ParamIntegrationTest: @Transactional;
    
    @Autowired
    private ParamDataOnDemand ParamIntegrationTest.dod;
    
    @Test
    public void ParamIntegrationTest.testCountParams() {
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        long count = com.gbd.union.domain.Param.countParams();
        org.junit.Assert.assertTrue("Counter for 'Param' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParamIntegrationTest.testFindParam() {
        com.gbd.union.domain.Param obj = dod.getRandomParam();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Param.findParam(id);
        org.junit.Assert.assertNotNull("Find method for 'Param' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Param' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParamIntegrationTest.testFindAllParams() {
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        long count = com.gbd.union.domain.Param.countParams();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Param', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.Param> result = com.gbd.union.domain.Param.findAllParams();
        org.junit.Assert.assertNotNull("Find all method for 'Param' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Param' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParamIntegrationTest.testFindParamEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        long count = com.gbd.union.domain.Param.countParams();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.Param> result = com.gbd.union.domain.Param.findParamEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Param' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Param' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParamIntegrationTest.testFlush() {
        com.gbd.union.domain.Param obj = dod.getRandomParam();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Param.findParam(id);
        org.junit.Assert.assertNotNull("Find method for 'Param' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParam(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Param' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParamIntegrationTest.testMerge() {
        com.gbd.union.domain.Param obj = dod.getRandomParam();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Param.findParam(id);
        boolean modified =  dod.modifyParam(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.Param merged = (com.gbd.union.domain.Param) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Param' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParamIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", dod.getRandomParam());
        com.gbd.union.domain.Param obj = dod.getNewTransientParam(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Param' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Param' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParamIntegrationTest.testRemove() {
        com.gbd.union.domain.Param obj = dod.getRandomParam();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Param' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Param.findParam(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Param' with identifier '" + id + "'", com.gbd.union.domain.Param.findParam(id));
    }
    
}
