// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.ResDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ResIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ResIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ResIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ResIntegrationTest: @Transactional;
    
    @Autowired
    private ResDataOnDemand ResIntegrationTest.dod;
    
    @Test
    public void ResIntegrationTest.testCountReses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", dod.getRandomRes());
        long count = com.gbd.union.domain.Res.countReses();
        org.junit.Assert.assertTrue("Counter for 'Res' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ResIntegrationTest.testFindRes() {
        com.gbd.union.domain.Res obj = dod.getRandomRes();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Res.findRes(id);
        org.junit.Assert.assertNotNull("Find method for 'Res' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Res' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ResIntegrationTest.testFindAllReses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", dod.getRandomRes());
        long count = com.gbd.union.domain.Res.countReses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Res', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.gbd.union.domain.Res> result = com.gbd.union.domain.Res.findAllReses();
        org.junit.Assert.assertNotNull("Find all method for 'Res' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Res' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ResIntegrationTest.testFindResEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", dod.getRandomRes());
        long count = com.gbd.union.domain.Res.countReses();
        if (count > 20) count = 20;
        java.util.List<com.gbd.union.domain.Res> result = com.gbd.union.domain.Res.findResEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Res' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Res' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ResIntegrationTest.testFlush() {
        com.gbd.union.domain.Res obj = dod.getRandomRes();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Res.findRes(id);
        org.junit.Assert.assertNotNull("Find method for 'Res' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRes(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Res' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ResIntegrationTest.testMerge() {
        com.gbd.union.domain.Res obj = dod.getRandomRes();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Res.findRes(id);
        boolean modified =  dod.modifyRes(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.gbd.union.domain.Res merged = (com.gbd.union.domain.Res) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Res' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ResIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", dod.getRandomRes());
        com.gbd.union.domain.Res obj = dod.getNewTransientRes(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Res' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Res' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ResIntegrationTest.testRemove() {
        com.gbd.union.domain.Res obj = dod.getRandomRes();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Res' failed to provide an identifier", id);
        obj = com.gbd.union.domain.Res.findRes(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Res' with identifier '" + id + "'", com.gbd.union.domain.Res.findRes(id));
    }
    
}
