// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gbd.union.domain;

import com.gbd.union.domain.Rule;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect RuleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RuleDataOnDemand: @Component;
    
    private Random RuleDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Rule> RuleDataOnDemand.data;
    
    public Rule RuleDataOnDemand.getNewTransientRule(int index) {
        com.gbd.union.domain.Rule obj = new com.gbd.union.domain.Rule();
        java.lang.String descn = "descn_" + index;
        if (descn.length() > 30) {
            descn  = descn.substring(0, 30);
        }
        obj.setDescn(descn);
        java.lang.String name = "name_" + index;
        if (name.length() > 20) {
            name  = name.substring(0, 20);
        }
        obj.setName(name);
        return obj;
    }
    
    public Rule RuleDataOnDemand.getSpecificRule(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Rule obj = data.get(index);
        return Rule.findRule(obj.getId());
    }
    
    public Rule RuleDataOnDemand.getRandomRule() {
        init();
        Rule obj = data.get(rnd.nextInt(data.size()));
        return Rule.findRule(obj.getId());
    }
    
    public boolean RuleDataOnDemand.modifyRule(Rule obj) {
        return false;
    }
    
    public void RuleDataOnDemand.init() {
        data = com.gbd.union.domain.Rule.findRuleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Rule' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.gbd.union.domain.Rule>();
        for (int i = 0; i < 10; i++) {
            com.gbd.union.domain.Rule obj = getNewTransientRule(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
